# Generated by Django 2.1.7 on 2019-03-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_vehicle', to='api.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='expected_duration_of_stay',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_quick_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='api.GuestVehicle'),
        ),
    ]
