# Generated by Django 2.1.7 on 2019-03-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guard_guardregistrationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guardregistrationtoken',
            name='guard',
        ),
        migrations.DeleteModel(
            name='Guard',
        ),
        migrations.DeleteModel(
            name='GuardRegistrationToken',
        ),
    ]
