# Generated by Django 2.1.7 on 2019-03-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190302_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationtoken',
            options={'default_related_name': 'registration_tokens'},
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='api.Flat'),
        ),
    ]
